version: '3.1'
services:
  stats-server:
    build: stats/stats-server
    image: ewm-stats-server
    container_name: ewm_stats_server_container
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    restart: on-failure
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ewm

  stats-db:
    image: postgres:14-alpine
    volumes:
      - stats-data:/var/lib/postgresql/data
    container_name: ewm_stats_db_container
    ports:
      - "6543:5432"
    environment:
      - POSTGRES_DB=ewm
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  ewm-service:
    build: main-service
    image: ewm-main-service
    container_name: ewm_main_service_container
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    restart: on-failure
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm
      - STATS_SERVER_URL=http://stats-server:9090

  ewm-db:
    build: main-service/postgres
    image: ewm-main-postgres
    volumes:
      - ewm-data:/var/lib/postgresql/data
    container_name: ewm_db_container
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=ewm
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

volumes:
  ewm-data:
  stats-data:
